当线程呈wait()状态时，调用线程对象的interrupt（）方法会出现InterruptedException异常

实验总结：
1. 执行完同步代码块就会释放对象的锁
2. 在执行同步代码块的过程中，遇到异常而导致终止，锁也会被释放
3. 在执行同步代码块的过程中，执行了锁所属对象的wait()方法，这个线程会释放对象所，而此线程对象会进入线程等待池中，等待被唤醒